receivable:
  supplemental_objects:
    - code: NGUYENKIM
      name: CTY NGUYEN KIM
      tax_code: "0109912477"
      aliases:
        - NGUYEN KIM
        - CTY NGUYEN KIM
        - "0109912477"
    - code: PTXDVATM
      name: CTY TNHH PTXD VA TM
      tax_code: "0101101999"
      aliases:
        - PTXD VA TM
        - CTY TNHH PTXD VA TM
        - "0101101999"
    - code: SAKAI
      name: CTY SAKAI
      aliases:
        - SAKAI
        - CTY SAKAI
    - code: CPVIETNAM
      name: CP VIETNAM CORPORATION
      aliases:
        - CP VIETNAM CORPORATION
    - code: DOSUNG
      name: DO SUNG MACHINERY
      aliases:
        - DO SUNG MACHINERY
    - code: LOGISTICS HUYANH
      name: CTY TNHH THUONG MAI VA DICH VU LOGISTICS HUY ANH
      aliases:
        - LOGISTICS HUY ANH
        - THUONG MAI VA DICH VU LOGISTICS HUY ANH
    - code: BAOHIEMAAA
      name: TONG CONG TY CO PHAN BAO HIEM AAA - CHI NHANH HAI PHONG
      aliases:
        - BAO HIEM AAA
        - BAO HIEM AAA HP

  aliases:
    PIL VN:
      - PIL VIETNAM CO LTD
      - PIL PAY INV
      - "0303449450"
    MINHPHONGHOPNHAT:
      - MINH PHONG HOP NHAT
      - CN HN CT TNHH MINH PHONG HOP NHAT
    MINHHUY:
      - MINH HUY
      - MINH HUY THANH TOAN TIEN THUE
    THANHPHONG:
      - CO SO THANH PHONG
      - THANH PHONG CHUYEN TIEN
    THONGMINHTCL:
      - TCL SMART DEVICE VIET NAM
      - TCL SMART DEVICE VIET NAM COMPANY LIMITED
    VEDAN VIETNAM:
      - HUU HAN VEDAN VIET NAM
      - VEDAN VIET NAM
    LOGISTICS HUYANH:
      - LOGISTICS HUY ANH
      - THUONG MAI VA DICH VU LOGISTICS HUY ANH
    OSSTEM INPLANT:
      - OSSTEM IMPLANT VI NA
      - OSSTEM IMPLANT VI NA OSSTEM
    BAOHIEMAAA:
      - BAO HIEM AAA
      - BAO HIEM AAA HP
    BONGSENVANG:
      - CT BONG SEN VANG
      - BONG SEN VANG
    QUOCTEQHP:
      - QHP
    NHIETDIENUONGBI:
      - NHIET DIEN UONG BI
      - CT NHIET DIEN UONG BI
    GIAONHAN AV:
      - CONG TY AV
      - AV THANH TOAN
    HANOSIMEX:
      - CP TMHAI PHONGHANOSIMEX
      - TMHAI PHONGHANOSIMEX

  exact_phrases:
    CTY NGUYEN KIM: NGUYENKIM
    PTXD VA TM: PTXDVATM
    PIL VIETNAM CO LTD: PIL VN
    TCL SMART DEVICE VIET NAM: THONGMINHTCL
    MINH HUY THANH TOAN TIEN THUE: MINHHUY
    CTY SAKAI: SAKAI
    CP VIETNAM CORPORATION: CPVIETNAM
    CO SO THANH PHONG: THANHPHONG
    DO SUNG MACHINERY: DOSUNG
    MINH PHONG HOP NHAT: MINHPHONGHOPNHAT
    HUU HAN VEDAN VIET NAM: VEDAN VIETNAM
    CTY TNHH THUONG MAI VA DICH VU LOGISTICS HUY ANH: LOGISTICS HUYANH
    THUONG MAI VA DICH VU LOGISTICS HUY ANH: LOGISTICS HUYANH
    OSSTEM IMPLANT VI NA OSSTEM: OSSTEM INPLANT
    OSSTEM IMPLANT VI NA: OSSTEM INPLANT
    BAO HIEM AAA HP: BAOHIEMAAA
    BAO HIEM AAA: BAOHIEMAAA
    CT BONG SEN VANG: BONGSENVANG
    BONG SEN VANG: BONGSENVANG
    QHP: QUOCTEQHP
    CT NHIET DIEN UONG BI: NHIETDIENUONGBI
    NHIET DIEN UONG BI: NHIETDIENUONGBI
    CONG TY AV: GIAONHAN AV
    AV THANH TOAN: GIAONHAN AV
    CP TMHAI PHONGHANOSIMEX: HANOSIMEX
    TMHAI PHONGHANOSIMEX: HANOSIMEX

payable:
  supplemental_objects:
    - code: MD
      name: CT CP HOA CHAT MINH DUC
      aliases:
        - HC MINH DUC
        - CT CP HC MINH DUC
    - code: PHANMEM
      name: DOI TUONG DAT COC PHAN MEM
      aliases:
        - DAT COC THIET KE PHAN MEM
        - PHAN MEM TU DONG HOA NGHIEP VU
    - code: CANGGAMA
      name: CANG GAMA
      aliases:
        - CANG GAMA
        - TT CANG GAMA

  aliases:
    VIETTHAG:
      - CT VIET THANG
      - VIET THANG
    THIENSON:
      - CT CHO THIEN SON
    VOIVIET:
      - CT CHO VOI VIET
      - VOI VIET
    "26868":
      - CT CHO 268
      - "268"
    MD:
      - HC MINH DUC
      - CT CP HC MINH DUC
    SGS:
      - SGS VIET NAM
    VSICO:
      - VSICO
    VTBNHATMINH:
      - CT CHO NHAT MINH
      - VTB NHAT MINH
    CANG-HP:
      - CT CP CANG HAI PHONG
    KDYT-HP:
      - KIEM DICH Y TE QUOC TE HAI PHONG
      - KIEM Y TE QUOC TE HAI PHONG
    VANTAITHUYSAOVIET:
      - VTT SAO VIET
      - VANTAITHUY SAO VIET
    VOI219:
      - VOI CONG NGHIEP VN 219
      - VOI CONG NGHIEP VIET NAM 219
    PETROLIMEX:
      - PETROLIMEX
    CVHH-QN:
      - CANG VU HH QUANG NINH
      - CANG VU HANG HAI QUANG NINH
    CANGSONDUONG:
      - CT DV HH SON DUONG
      - DV HH SON DUONG
      - DVHH SON DUONG
    QUOCTENGHISON:
      - CANG QT NGHI SON
      - CANG QUOC TE NGHI SON
    ANPHAT:
      - CT AN PHAT
    THANHDO:
      - THANH DO
    KSDAIDUONG:
      - CPDTKS DAI DUONG
      - CTCP DT KS DAI DUONG
      - CTY CPDTKS DAI DUONG
      - CP DT KS DAI DUONG
    SME:
      - CPTV SME
      - CTY CPTV SME
    VIENTHONG MOBIFONE:
      - MOBIFONE
      - CUOC MOBIFONE
    VNPTHAIPHONG:
      - VIEN THONG VNPT
      - CUOC VIEN THONG VNPT
    TANTHANHDAT:
      - DVVTHH TAN THANH DAT
      - CT DVVTHH TAN THANH DAT
      - TAN THANH DAT
    VATTUNHATMINH:
      - TM VT VT NHAT MINH
      - CT TM VT VT NHAT MINH
    TRANGNGUYEN:
      - CTCP TMVT TRANG NGUYEN
      - TMVT TRANG NGUYEN
    HOATIEU6:
      - HOA TIEU KV VI
      - HOA TIEU KHU VUC VI
    CAPNUOC:
      - THANH TOAN TIEN DIEN KY HOA DON THANG
    BUUDIEN:
      - BUU DIEN TP HP
      - BUU DIEN THANH PHO HAI PHONG

  exact_phrases:
    CT VIET THANG: VIETTHAG
    CT CHO THIEN SON: THIENSON
    CT CHO VOI VIET: VOIVIET
    CT CHO 268: "26868"
    HC MINH DUC: MD
    SGS VIET NAM: SGS
    DAT COC THIET KE PHAN MEM: PHANMEM
    TT CUOC BIEN CHO VSICO: VSICO
    CT CHO NHAT MINH: VTBNHATMINH
    TT CANG GAMA: CANGGAMA
    CT CP CANG HAI PHONG: CANG-HP
    KIEM DICH Y TE QUOC TE HAI PHONG: KDYT-HP
    KIEM Y TE QUOC TE HAI PHONG: KDYT-HP
    VTT SAO VIET: VANTAITHUYSAOVIET
    VOI CONG NGHIEP VN 219: VOI219
    VOI CONG NGHIEP VIET NAM 219: VOI219
    PETROLIMEX: PETROLIMEX
    VTB NHAT MINH: VTBNHATMINH
    CANG VU HH QUANG NINH: CVHH-QN
    CANG VU HANG HAI QUANG NINH: CVHH-QN
    CT DV HH SON DUONG: CANGSONDUONG
    DV HH SON DUONG: CANGSONDUONG
    DVHH SON DUONG: CANGSONDUONG
    CANG QT NGHI SON: QUOCTENGHISON
    CANG QUOC TE NGHI SON: QUOCTENGHISON
    CT AN PHAT: ANPHAT
    THANH DO: THANHDO
    CPDTKS DAI DUONG: KSDAIDUONG
    CTCP DT KS DAI DUONG: KSDAIDUONG
    CTY CPDTKS DAI DUONG: KSDAIDUONG
    CP DT KS DAI DUONG: KSDAIDUONG
    CPTV SME: SME
    CTY CPTV SME: SME
    MOBIFONE: VIENTHONG MOBIFONE
    CUOC MOBIFONE: VIENTHONG MOBIFONE
    VIEN THONG VNPT: VNPTHAIPHONG
    CUOC VIEN THONG VNPT: VNPTHAIPHONG
    DVVTHH TAN THANH DAT: TANTHANHDAT
    CT DVVTHH TAN THANH DAT: TANTHANHDAT
    TAN THANH DAT: TANTHANHDAT
    TM VT VT NHAT MINH: VATTUNHATMINH
    CT TM VT VT NHAT MINH: VATTUNHATMINH
    CTCP TMVT TRANG NGUYEN: TRANGNGUYEN
    TMVT TRANG NGUYEN: TRANGNGUYEN
    HOA TIEU KV VI: HOATIEU6
    HOA TIEU KHU VUC VI: HOATIEU6
    THANH TOAN TIEN DIEN KY HOA DON THANG: CAPNUOC
    BUU DIEN TP HP: BUUDIEN
    BUU DIEN THANH PHO HAI PHONG: BUUDIEN
