own_company:
  object_codes:
    - "LE PHAM"
  tax_codes:
    - "0200410388"
  aliases:
    - "LE PHAM"
    - "LEPHAM"
    - "CTY LE PHAM"
    - "CTY LEPHAM"
    - "CTY TNHH LE PHAM"
    - "CT TNHH LE PHAM"
    - "CONG TY TNHH LE PHAM"
    - "CONG TY TRACH NHIEM HUU HAN LE PHAM"
    - "CÔNG TY TNHH LÊ PHẠM"
    - "CÔNG TY TRÁCH NHIỆM HỮU HẠN LÊ PHẠM"
